BadgerCloudService/Controllers/DistributorlistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;

namespace BadgerCloudService.Controllers
{
    public class DistributorListController : Controller
    {
        private readonly string DistributorLocation = SettingConfig.GetSetting("DistributorLocation");
        private readonly string DistributorFileName = SettingConfig.GetSetting("DistributorFileName");

        public ActionResult Index()
        {
            return View();
        } 

        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            if (!Directory.Exists(Server.MapPath(this.DistributorLocation)))
            {
                Directory.CreateDirectory(Server.MapPath(this.DistributorLocation));
            }

            string path = System.IO.Path.Combine(Server.MapPath(this.DistributorLocation), System.IO.Path.GetFileName(this.DistributorFileName));
            file.SaveAs(path);
            ViewBag.Message = "File uploaded successfully";
            return View();
        }
    }
}

BadgerCloudService/Views/Distributorlist/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Distributor List</h2>
<h4>The distributor list provided by marketing should contain the list of available distributors</h4>

@using (Html.BeginForm("Index", "DistributorList", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <label class="col-md-2" for="file">Upload File:</label>
    <input class="col-md-3" type="file" name="file" id="file" accept=".xls" />
    <input class="btn btn-success btn-sm" type="submit" value="Upload File" />
    @ViewBag.Message
}