BadgerCloudService/Controllers/AttendeesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BadgerCloudService.Models;
using BadgerCloudService.Models.DAL;
using BadgerCloudService.Models.Context;
using BadgerCloudService.Objects.Filters;
using BadgerCloudService.Objects.Filters.AttendeeFilters;

namespace BadgerCloudService.Controllers
{
    public class AttendeesController : Controller
    {
        private IRepository db = new Repository();

        // GET: Attendees
        public ActionResult Index()
        {
            return View(db.GetAttendees());
        }

        [HttpPost]
        public ActionResult Search(string Data)
        {
            IFilter<Attendee> filter = new NameFilter(Data);
            return PartialView("Templates/Attendees/AttendeesTable", db.GetFilteredAttendees(filter));
        }

        // GET: Attendees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendee attendee = db.FindAttendee(id);
            if (attendee == null)
            {
                return HttpNotFound();
            }

            ViewBag.Questions = this.db.GetQuestions();
            return View(attendee);
        }

        // GET: Attendees/Create
        public ActionResult Create()
        {
            return View();
        }

        // GET: Attendees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendee attendee = db.FindAttendee(id);
            if (attendee == null)
            {
                return HttpNotFound();
            }
            return View(attendee);
        }

        // POST: Attendees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,BadgeId,FirstName,LastName,Title,Company,Division,Email,PhoneNumber,Fax,RegistrationType,Notes,Address_Id,Event_Id,Distributor_Id")] Attendee attendee)
        {
            if (ModelState.IsValid)
            {
                db.UpdateAttendee(attendee);
                return RedirectToAction("Index");
            }
            return View(attendee);
        }

        // GET: Attendees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Attendee attendee = db.FindAttendee(id);
            if (attendee == null)
            {
                return HttpNotFound();
            }
            return View(attendee);
        }

        // POST: Attendees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            db.RemoveAttendee(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BadgerCloudService/Controllers/LeadsController.cs
using BadgerCloudService.Library;
using BadgerCloudService.Models.DAL;
using BadgerCloudService.Objects;
using BadgerCloudService.Objects.Filters.Leads;
using BadgerCloudService.Objects.Filters;
using BadgerCloudService.Services.DistributorSources;
using BadgerCloudService.ViewModels;
using System.Collections.Generic;
using System.Web.Mvc;

namespace BadgerCloudService.Controllers
{
    public class LeadsController : Controller
    {
        private IRepository _repo;
        private IDistributorList _distributors;

        public LeadsController()
        {
            this._repo = new Repository();
            this._distributors = new DistributorList();
        }

        public LeadsController(IRepository repo, IDistributorList distributorList)
        {
            this._repo = repo;
            this._distributors = distributorList;
        }

        // GET: Leads
        public ActionResult Index()
        {
            this.ViewBag.Distributors = this.GetDistributorNameList();
            this.ViewBag.Machines = this.GetMachineList();
            return View(this._repo.GetLeadList());
        }

        public ActionResult GetList(FilterViewModel[] filtersVm)
        {
            List<IFilter<Lead>> filters = LeadFilterFactory.CreateFilters(filtersVm);
            IEnumerable<Lead> leads = this._repo.GetFilteredLeads(filters);
            return PartialView("Templates/Leads/LeadsList", leads);
        }

        private List<SelectListItem> GetMachineList()
        {
            return MachineDropDownListContents.GetMachineNameListContents(this._repo);
        }

        private List<SelectListItem> GetDistributorNameList()
        {
            return DistributorDropDownContents.GetDistributorNameList(this._distributors);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _repo.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BadgerCloudService/Views/Shared/Templates/Leads/LeadsList.cshtml
@model IEnumerable<BadgerCloudService.Objects.Lead>
<div id="LeadsList">
    <table class="table">
        <thead>
            <tr>
                <th>
                    Name
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Machine)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Distributor)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DistributorBranch)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.VisitCount)
                </th>
            </tr>
        </thead>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink((item.FirstName + " " + item.LastName), "Details", "Attendees", new { id = item.Id }, new { })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Machine)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Distributor)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DistributorBranch)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.VisitCount)
                </td>
            </tr>
        }
    </table>
</div>

BadgerCloudService/Views/Shared/Templates/Leads/LeadsListControls.cshtml
@Scripts.Render("~/Scripts/JS/Filters.js")
<div>

    <h3>Filters</h3>
    <div class="col-md-10 form-group">
        <label class="col-md-2">Add Filter:</label>
        <select id="filterDropdown">
            <option value="default">Select a Filter</option>
            <option value="DateFilter">Date</option>
            <option value="DistributorFilter">Distributors</option>
            <option value="MachineFilter">Machines</option>
            <option value="NameFilter">Name</option>
            <option value="EventFilter">Event</option>
        </select>
        <button class="btn-group-sm btn-primary" onclick="addFilter($('#filterDropdown option:selected').val())">Add</button>
        <button class="btn-group-sm btn-success" onclick="FilterLeadList();">Filter</button>
        <button class="btn-group-sm btn-info" onclick="ExportListToExcel();">Export</button>
    </div>

    <form id="Filters" class="form-group"></form>

    @Html.Partial("Templates/Leads/LeadsList")
</div>